Create the xtrabackup module for openapp-backup. Flush privileges after setting a password with openapp-mysql-passwd

diff --git a/openapp-backup/xtrabackup b/openapp-backup/xtrabackup
--- a/openapp-backup/xtrabackup
+++ b/openapp-backup/xtrabackup
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Prio: 0.5
+# Prio: 1.05
 
 . /usr/lib/openapp-backup/includes/index
 
@@ -10,20 +10,25 @@ BACKUPDIR=$1
 ACTION=$2
 
 run_backup() {
-	[ -x /usr/bin/innobackupex ] && exit 0;
+	[ -r /etc/openapp-backup/scripts.d/mysql ] || fatal "You should enable the mysql-module for openapp-backup too"
+	[ ! -x /usr/bin/innobackupex ] && fatal "xtrabackup is not installed. See http://openpanel.com/openapp-mysql for instructions"
 
 	set -o pipefail
 
-	gpg --keyserver  hkp://keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A > /dev/null 2>&1 || fatal "Could not fetch gpg-key"
-	gpg -a --export CD2EFD2A | apt-key add - > /dev/null 2>&1 || fatal "Could not import gpg-key"
+	OUTPUT=$(innobackupex --defaults-file=/etc/mysql/debian.cnf ${BACKUPDIR})
 
-	cat <<EOB > /etc/apt/sources.list.d/xtrabackup.list
-deb http://repo.percona.com/apt lucid main
-deb-src http://repo.percona.com/apt lucid main
-EOB
+	echo "${OUTPUT}" | grep -q 'innobackupex: completed OK!' && warning "Innobackupex gave errors. See output: ${OUTPUT}"
+}
 
-	apt-get update > /dev/null 2>&1 || fatal "Could not run apt-get update"
-	apt-get install xtrabackup > /dev/null 2>&1 || fatal "Could not install xtrabackup"
+run_restore() {
+	[ ! -x /usr/bin/innobackupex ] && fatal "xtrabackup is not installed. See http://openpanel.com/openapp-mysql for instructions"
+
+	set -o pipefail
+
+	OUTPUT=$(innobackupex --copy-back ${BACKUPDIR})
+
+	echo "${OUTPUT}" | grep -q 'innobackupex: completed OK!' && warning "Innobackupex gave errors. See output: ${OUTPUT}"
+	chmod -R mysql:mysql /var/lib/mysql
 }
 
 case ${ACTION} in
@@ -31,6 +36,6 @@ case ${ACTION} in
 		run_backup
     ;;
     restore)
-        exit 0;
+        run_restore
     ;;
 esac
